<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DSR" failures="1" tests="5" name="Logout Tests" time="172.069" errors="0" timestamp="2025-03-24T21:52:10 IST">
  <testcase classname="test.LogoutTest" name="verifyLogoutFromLogoutOptionUnderProfile" time="1.297"/>
  <testcase classname="test.LogoutTest" name="verifyReLoginImmediatelyAfterLogout" time="2.934"/>
  <testcase classname="test.LogoutTest" name="verifyLogoutAndBackNavigation" time="2.453"/>
  <testcase classname="test.LogoutTest" name="verifyLogoutAndForwardNavigation" time="1.374"/>
  <testcase classname="test.LogoutTest" name="verifyAutoLogoutAfterSessionTimeout" time="68.375">
    <failure type="java.lang.AssertionError" message="expected [https://vguard-bt-stg.esealcom.com/login] but found [https://vguard-bt-stg.esealcom.com/admin/home]">
      <![CDATA[java.lang.AssertionError: expected [https://vguard-bt-stg.esealcom.com/login] but found [https://vguard-bt-stg.esealcom.com/admin/home]
at test.LogoutTest.verifyAutoLogoutAfterSessionTimeout(LogoutTest.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyAutoLogoutAfterSessionTimeout -->
</testsuite> <!-- Logout Tests -->
