<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DSR" failures="6" tests="25" name="Users Tests" time="1550.588" errors="0" timestamp="2025-03-26T01:44:47 IST">
  <testcase classname="test.UsersTest" name="verifyAddUserFormFieldPlaceholders" time="1.581"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithEmptySpacesInFields" time="2.628"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithExistingEmail" time="3.024">
    <failure type="java.lang.AssertionError" message="expected [Email is already exists] but found [User name is already exists]">
      <![CDATA[java.lang.AssertionError: expected [Email is already exists] but found [User name is already exists]
at test.UsersTest.verifyAddUserWithExistingEmail(UsersTest.java:218)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserWithExistingEmail -->
  <testcase classname="test.UsersTest" name="verifyAddUserWithExistingUserName" time="3.357"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithInvalidEmailFormat" time="2.62"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithInvalidPhoneNumber" time="2.833"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithLongUserName" time="2.896"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithMismatchedPassword" time="2.784"/>
  <testcase classname="test.UsersTest" name="verifyAddUserWithValidData" time="2.908">
    <failure type="java.lang.AssertionError" message="expected [Successfully submitted!] but found [User name is already exists]">
      <![CDATA[java.lang.AssertionError: expected [Successfully submitted!] but found [User name is already exists]
at test.UsersTest.verifyAddUserWithValidData(UsersTest.java:176)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserWithValidData -->
  <testcase classname="test.UsersTest" name="verifyCloseAddUserUsingCloseButtonWithEnterDeatils" time="12.54"/>
  <testcase classname="test.UsersTest" name="verifyCloseAddUserUsingCloseIconWithEnterDeatils" time="12.606"/>
  <testcase classname="test.UsersTest" name="verifyCloseAddUserWithoutEnteringDetailsUsingCloseButton" time="10.968"/>
  <testcase classname="test.UsersTest" name="verifyCloseAddUserWithoutEnteringDetailsUsingCloseIcon" time="11.029"/>
  <testcase classname="test.UsersTest" name="verifyDeleteUser" time="440.992"/>
  <testcase classname="test.UsersTest" name="verifyFieldLabelAndAsteriskSymbolForMandatoryFieldsInAddUserPage" time="1.908"/>
  <testcase classname="test.UsersTest" name="verifyNavigationToAddUserPage" time="1.604"/>
  <testcase classname="test.UsersTest" name="verifyUsersModuleDetails" time="0.439">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Users Page URL is mismatched expected [https://vguard-bt-stg.esealcom.com/null] but found [https://vguard-bt-stg.esealcom.com/admin/authorization/users],
	Users Page Heading mismatchd expected [null] but found [User Management]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Users Page URL is mismatched expected [https://vguard-bt-stg.esealcom.com/null] but found [https://vguard-bt-stg.esealcom.com/admin/authorization/users],
Users Page Heading mismatchd expected [null] but found [User Management]
at test.UsersTest.verifyUsersModuleDetails(UsersTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyUsersModuleDetails -->
  <testcase classname="test.UsersTest" name="verifyUsersModuleFooterSection" time="0.06"/>
  <testcase classname="test.UsersTest" name="verifyNavigationToUsersModule" time="1.016"/>
  <testcase classname="test.UsersTest" name="verifyMandatoryFieldAlertsInAddUser" time="2.876"/>
  <testcase classname="test.UsersTest" name="verifyMandatoryFieldValidationForUpdatePassword" time="429.282">
    <failure type="org.openqa.selenium.NoSuchElementException" message="no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//*[text()=&amp;apos;Save&amp;apos;]&amp;quot;}
  (Session info: chrome=134.0.6998.118)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.28.1&amp;apos;, revision: &amp;apos;73f5ad48a2&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.2&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [aa0fea0e82573fda7d44a8f125ceea73, findElement {using=xpath, value=//*[text()=&amp;apos;Save&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 134.0.6998.118, chrome: {chromedriverVersion: 134.0.6998.165 (fd886e2cb29..., userDataDir: C:\Users\dusan\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50461}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50461/devtoo..., se:cdpVersion: 134.0.6998.118, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: aa0fea0e82573fda7d44a8f125ceea73">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[text()='Save']"}
  (Session info: chrome=134.0.6998.118)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.28.1', revision: '73f5ad48a2'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [aa0fea0e82573fda7d44a8f125ceea73, findElement {using=xpath, value=//*[text()='Save']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 134.0.6998.118, chrome: {chromedriverVersion: 134.0.6998.165 (fd886e2cb29..., userDataDir: C:\Users\dusan\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50461}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50461/devtoo..., se:cdpVersion: 134.0.6998.118, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: aa0fea0e82573fda7d44a8f125ceea73
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy28.isDisplayed(Unknown Source)
at utils.ElementUtilities.isElementDisplayedOnPage(ElementUtilities.java:169)
at utils.ElementUtilities.clickOnElement(ElementUtilities.java:128)
at pages.UsersPage.clickOnSaveButton(UsersPage.java:276)
at test.UsersTest.verifyMandatoryFieldValidationForUpdatePassword(UsersTest.java:408)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyMandatoryFieldValidationForUpdatePassword -->
  <testcase classname="test.UsersTest" name="verifyAddUserUsingLeadingAndTrailingSpaces" time="3.072">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [atbs] but found [  atbs  ]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [atbs] but found [  atbs  ]
at test.UsersTest.verifyAddUserUsingLeadingAndTrailingSpaces(UsersTest.java:440)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddUserUsingLeadingAndTrailingSpaces -->
  <testcase classname="test.UsersTest" name="verifySearchUser" time="1.007"/>
  <testcase classname="test.UsersTest" name="verifySavedUserDetailsInEditWindow" time="12.549">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [atbs] but found [A B Traders],
	expected [dasfd] but found [Plant],
	expected [1234567890] but found [9948021022],
	expected [abc@yomail.com] but found [Kolkota@plant.com],
	expected [userss] but found [100013],
	expected [Plant] but found [null],
	expected [VCPL - Panthnagar] but found [null],
	expected [None] but found [null],
	expected [Testing role] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [atbs] but found [A B Traders],
expected [dasfd] but found [Plant],
expected [1234567890] but found [9948021022],
expected [abc@yomail.com] but found [Kolkota@plant.com],
expected [userss] but found [100013],
expected [Plant] but found [null],
expected [VCPL - Panthnagar] but found [null],
expected [None] but found [null],
expected [Testing role] but found [null]
at test.UsersTest.verifySavedUserDetailsInEditWindow(UsersTest.java:484)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifySavedUserDetailsInEditWindow -->
  <testcase classname="test.UsersTest" name="verifyUserInUsersModuleGridWithPagination" time="400.941"/>
</testsuite> <!-- Users Tests -->
