<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="35" passed="22" failed="13" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-19T20:44:49 IST" name="Smoke" finished-at="2025-03-19T22:03:25 IST" duration-ms="4716755">
    <groups>
      <group name="Sanity">
        <method signature="LogoutTest.verifyLogoutAndBackNavigation()[pri:3, instance:test.LogoutTest@ba2f4ec]" name="verifyLogoutAndBackNavigation" class="test.LogoutTest"/>
        <method signature="LogoutTest.verifyLogoutAndForwardNavigation()[pri:4, instance:test.LogoutTest@ba2f4ec]" name="verifyLogoutAndForwardNavigation" class="test.LogoutTest"/>
        <method signature="LogoutTest.verifyAutoLogoutAfterSessionTimeout()[pri:5, instance:test.LogoutTest@ba2f4ec]" name="verifyAutoLogoutAfterSessionTimeout" class="test.LogoutTest"/>
        <method signature="LoginTest.verifyLoginWithBlankCredentials()[pri:7, instance:test.LoginTest@49438269]" name="verifyLoginWithBlankCredentials" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithEmailOnly()[pri:8, instance:test.LoginTest@49438269]" name="verifyLoginWithEmailOnly" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithPasswordOnly()[pri:9, instance:test.LoginTest@49438269]" name="verifyLoginWithPasswordOnly" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithShortPassword()[pri:10, instance:test.LoginTest@49438269]" name="verifyLoginWithShortPassword" class="test.LoginTest"/>
      </group> <!-- Sanity -->
      <group name="Sanity1">
        <method signature="LoginTest.verifyLoginUsingInvalidCredentials()[pri:4, instance:test.LoginTest@49438269]" name="verifyLoginUsingInvalidCredentials" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithInvalidEmailAndValidPassword()[pri:5, instance:test.LoginTest@49438269]" name="verifyLoginWithInvalidEmailAndValidPassword" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithValidEmailAndInvalidPassword()[pri:6, instance:test.LoginTest@49438269]" name="verifyLoginWithValidEmailAndInvalidPassword" class="test.LoginTest"/>
      </group> <!-- Sanity1 -->
      <group name="Smoke">
        <method signature="LoginTest.verifyLoginPageTitleAndUrl()[pri:1, instance:test.LoginTest@49438269]" name="verifyLoginPageTitleAndUrl" class="test.LoginTest"/>
        <method signature="LogoutTest.verifyLogoutFromLogoutOptionUnderProfile()[pri:1, instance:test.LogoutTest@ba2f4ec]" name="verifyLogoutFromLogoutOptionUnderProfile" class="test.LogoutTest"/>
        <method signature="LoginTest.verifyFieldAndCheckboxLabels()[pri:2, instance:test.LoginTest@49438269]" name="verifyFieldAndCheckboxLabels" class="test.LoginTest"/>
        <method signature="LogoutTest.verifyReLoginImmediatelyAfterLogout()[pri:2, instance:test.LogoutTest@ba2f4ec]" name="verifyReLoginImmediatelyAfterLogout" class="test.LogoutTest"/>
        <method signature="LoginTest.verifyLoginUsingValidCredentials()[pri:3, instance:test.LoginTest@49438269]" name="verifyLoginUsingValidCredentials" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithUppercaseInsensitiveEmail()[pri:11, instance:test.LoginTest@49438269]" name="verifyLoginWithUppercaseInsensitiveEmail" class="test.LoginTest"/>
        <method signature="LoginTest.verifyLoginWithLowercaseInsensitiveEmail()[pri:12, instance:test.LoginTest@49438269]" name="verifyLoginWithLowercaseInsensitiveEmail" class="test.LoginTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2025-03-19T20:44:49 IST" name="Test" finished-at="2025-03-19T22:03:25 IST" duration-ms="4716755">
      <class name="test.UsersTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:02:46 IST" name="setup" finished-at="2025-03-19T21:03:59 IST" duration-ms="73320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyDeleteUser()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:03:59 IST" name="verifyDeleteUser" finished-at="2025-03-19T21:11:19 IST" duration-ms="439506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDeleteUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:11:19 IST" name="tearDown" finished-at="2025-03-19T21:11:19 IST" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:11:19 IST" name="setup" finished-at="2025-03-19T21:12:11 IST" duration-ms="51985" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyNavigationToUsersModule()[pri:1, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:12:11 IST" name="verifyNavigationToUsersModule" finished-at="2025-03-19T21:12:12 IST" duration-ms="1424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavigationToUsersModule -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:12:12 IST" name="tearDown" finished-at="2025-03-19T21:12:13 IST" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:12:13 IST" name="setup" finished-at="2025-03-19T21:13:13 IST" duration-ms="60134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddUserWithValidDetails()[pri:2, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:13:13 IST" name="verifyAddUserWithValidDetails" finished-at="2025-03-19T21:13:16 IST" duration-ms="3660" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Successfully submitted!] but found [User name is already exists]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Successfully submitted!] but found [User name is already exists]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.UsersTest.verifyAddUserWithValidDetails(UsersTest.java:82)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserWithValidDetails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:13:16 IST" name="tearDown" finished-at="2025-03-19T21:13:17 IST" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:13:17 IST" name="setup" finished-at="2025-03-19T21:14:24 IST" duration-ms="67536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyMandatoryFieldValidationForAddUser()[pri:4, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:14:24 IST" name="verifyMandatoryFieldValidationForAddUser" finished-at="2025-03-19T21:14:26 IST" duration-ms="2090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMandatoryFieldValidationForAddUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:14:26 IST" name="tearDown" finished-at="2025-03-19T21:14:26 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:14:26 IST" name="setup" finished-at="2025-03-19T21:15:36 IST" duration-ms="69306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyMandatoryFieldValidationForUpdatePassword()[pri:4, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:15:36 IST" name="verifyMandatoryFieldValidationForUpdatePassword" finished-at="2025-03-19T21:22:52 IST" duration-ms="435820" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at test.UsersTest.verifyMandatoryFieldValidationForUpdatePassword(UsersTest.java:135)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMandatoryFieldValidationForUpdatePassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:22:52 IST" name="tearDown" finished-at="2025-03-19T21:22:52 IST" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:22:52 IST" name="setup" finished-at="2025-03-19T21:23:37 IST" duration-ms="45592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddUserUsingLeadingAndTrailingSpaces()[pri:5, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:23:37 IST" name="verifyAddUserUsingLeadingAndTrailingSpaces" finished-at="2025-03-19T21:23:41 IST" duration-ms="3062" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [atbs] but found [  atbs  ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [atbs] but found [  atbs  ]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.UsersTest.verifyAddUserUsingLeadingAndTrailingSpaces(UsersTest.java:168)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserUsingLeadingAndTrailingSpaces -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:23:41 IST" name="tearDown" finished-at="2025-03-19T21:23:41 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:23:41 IST" name="setup" finished-at="2025-03-19T21:24:42 IST" duration-ms="61247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySearchUser()[pri:6, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:24:42 IST" name="verifySearchUser" finished-at="2025-03-19T21:24:42 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearchUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:24:42 IST" name="tearDown" finished-at="2025-03-19T21:24:42 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:24:42 IST" name="setup" finished-at="2025-03-19T21:25:45 IST" duration-ms="62270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySavedUserDetailsInEditWindow()[pri:7, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:25:45 IST" name="verifySavedUserDetailsInEditWindow" finished-at="2025-03-19T21:32:51 IST" duration-ms="426887" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Plant] but found [null],
expected [VCPL - Panthnagar] but found [null],
expected [None] but found [null],
expected [Testing role] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Plant] but found [null],
expected [VCPL - Panthnagar] but found [null],
expected [None] but found [null],
expected [Testing role] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.UsersTest.verifySavedUserDetailsInEditWindow(UsersTest.java:207)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySavedUserDetailsInEditWindow -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:32:52 IST" name="tearDown" finished-at="2025-03-19T21:32:52 IST" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:32:52 IST" name="setup" finished-at="2025-03-19T21:34:00 IST" duration-ms="68328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyUserInUsersModuleGridWithPagination()[pri:8, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:34:00 IST" name="verifyUserInUsersModuleGridWithPagination" finished-at="2025-03-19T21:40:38 IST" duration-ms="397959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserInUsersModuleGridWithPagination -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.UsersTest@367ffa75]" started-at="2025-03-19T21:40:38 IST" name="tearDown" finished-at="2025-03-19T21:40:38 IST" duration-ms="278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.UsersTest -->
      <class name="test.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:40:38 IST" name="setup" finished-at="2025-03-19T21:41:47 IST" duration-ms="68499" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginPageTitleAndUrl()[pri:1, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:41:47 IST" name="verifyLoginPageTitleAndUrl" finished-at="2025-03-19T21:41:47 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleAndUrl -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:41:47 IST" name="tearDown" finished-at="2025-03-19T21:41:47 IST" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:41:47 IST" name="setup" finished-at="2025-03-19T21:43:01 IST" duration-ms="73851" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyFieldAndCheckboxLabels()[pri:2, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:43:01 IST" name="verifyFieldAndCheckboxLabels" finished-at="2025-03-19T21:43:01 IST" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFieldAndCheckboxLabels -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:43:01 IST" name="tearDown" finished-at="2025-03-19T21:43:01 IST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:43:01 IST" name="setup" finished-at="2025-03-19T21:43:47 IST" duration-ms="45405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginUsingValidCredentials()[pri:3, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:43:47 IST" name="verifyLoginUsingValidCredentials" finished-at="2025-03-19T21:43:48 IST" duration-ms="1036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginUsingValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:43:48 IST" name="tearDown" finished-at="2025-03-19T21:43:48 IST" duration-ms="158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:43:48 IST" name="setup" finished-at="2025-03-19T21:44:50 IST" duration-ms="62582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginUsingInvalidCredentials()[pri:4, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:44:50 IST" name="verifyLoginUsingInvalidCredentials" finished-at="2025-03-19T21:44:52 IST" duration-ms="1365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginUsingInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:44:52 IST" name="tearDown" finished-at="2025-03-19T21:44:52 IST" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:44:52 IST" name="setup" finished-at="2025-03-19T21:46:38 IST" duration-ms="105801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithInvalidEmailAndValidPassword()[pri:5, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:46:38 IST" name="verifyLoginWithInvalidEmailAndValidPassword" finished-at="2025-03-19T21:46:49 IST" duration-ms="11439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidEmailAndValidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:46:49 IST" name="tearDown" finished-at="2025-03-19T21:46:49 IST" duration-ms="206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:46:49 IST" name="setup" finished-at="2025-03-19T21:47:48 IST" duration-ms="58624" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithValidEmailAndInvalidPassword()[pri:6, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:47:48 IST" name="verifyLoginWithValidEmailAndInvalidPassword" finished-at="2025-03-19T21:47:59 IST" duration-ms="10971" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidEmailAndInvalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:47:59 IST" name="tearDown" finished-at="2025-03-19T21:47:59 IST" duration-ms="178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:47:59 IST" name="setup" finished-at="2025-03-19T21:49:30 IST" duration-ms="90308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithBlankCredentials()[pri:7, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:49:30 IST" name="verifyLoginWithBlankCredentials" finished-at="2025-03-19T21:49:30 IST" duration-ms="414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithBlankCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:49:30 IST" name="tearDown" finished-at="2025-03-19T21:49:30 IST" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:49:30 IST" name="setup" finished-at="2025-03-19T21:51:02 IST" duration-ms="92246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithEmailOnly()[pri:8, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:51:02 IST" name="verifyLoginWithEmailOnly" finished-at="2025-03-19T21:51:03 IST" duration-ms="350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithEmailOnly -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:51:03 IST" name="tearDown" finished-at="2025-03-19T21:51:03 IST" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:51:03 IST" name="setup" finished-at="2025-03-19T21:52:38 IST" duration-ms="95057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithPasswordOnly()[pri:9, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:52:38 IST" name="verifyLoginWithPasswordOnly" finished-at="2025-03-19T21:52:38 IST" duration-ms="326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithPasswordOnly -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:52:38 IST" name="tearDown" finished-at="2025-03-19T21:52:38 IST" duration-ms="165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:52:38 IST" name="setup" finished-at="2025-03-19T21:54:15 IST" duration-ms="96254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithShortPassword()[pri:10, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:54:15 IST" name="verifyLoginWithShortPassword" finished-at="2025-03-19T21:54:15 IST" duration-ms="469" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithShortPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:54:15 IST" name="tearDown" finished-at="2025-03-19T21:54:15 IST" duration-ms="160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:54:15 IST" name="setup" finished-at="2025-03-19T21:55:44 IST" duration-ms="88427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithUppercaseInsensitiveEmail()[pri:11, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:55:44 IST" name="verifyLoginWithUppercaseInsensitiveEmail" finished-at="2025-03-19T21:55:45 IST" duration-ms="929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithUppercaseInsensitiveEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:55:45 IST" name="tearDown" finished-at="2025-03-19T21:55:45 IST" duration-ms="152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:55:45 IST" name="setup" finished-at="2025-03-19T21:56:46 IST" duration-ms="60785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginWithLowercaseInsensitiveEmail()[pri:12, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:56:46 IST" name="verifyLoginWithLowercaseInsensitiveEmail" finished-at="2025-03-19T21:56:47 IST" duration-ms="923" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithLowercaseInsensitiveEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LoginTest@49438269]" started-at="2025-03-19T21:56:47 IST" name="tearDown" finished-at="2025-03-19T21:56:47 IST" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.LoginTest -->
      <class name="test.TransactionsTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:44:49 IST" name="setup" finished-at="2025-03-19T20:45:45 IST" duration-ms="56131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyNavigationToUsersModule()[pri:1, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:45:45 IST" name="verifyNavigationToUsersModule" finished-at="2025-03-19T20:45:46 IST" duration-ms="759" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavigationToUsersModule -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:45:46 IST" name="tearDown" finished-at="2025-03-19T20:45:46 IST" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:45:46 IST" name="setup" finished-at="2025-03-19T20:46:25 IST" duration-ms="39225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddTransactionWithValidData()[pri:2, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:46:25 IST" name="verifyAddTransactionWithValidData" finished-at="2025-03-19T20:46:28 IST" duration-ms="3485" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Successfully submitted!] but found [Feature Code already exists]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Successfully submitted!] but found [Feature Code already exists]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.TransactionsTest.verifyAddTransactionWithValidData(TransactionsTest.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddTransactionWithValidData -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:46:29 IST" name="tearDown" finished-at="2025-03-19T20:46:30 IST" duration-ms="1730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:46:30 IST" name="setup" finished-at="2025-03-19T20:47:36 IST" duration-ms="65818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddUserWithDuplicateTransactionName()[pri:3, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:47:36 IST" name="verifyAddUserWithDuplicateTransactionName" finished-at="2025-03-19T20:47:40 IST" duration-ms="4093" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Transaction name is already exists] but found [Transaction Name already exists]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Transaction name is already exists] but found [Transaction Name already exists]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.TransactionsTest.verifyAddUserWithDuplicateTransactionName(TransactionsTest.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserWithDuplicateTransactionName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:47:40 IST" name="tearDown" finished-at="2025-03-19T20:47:41 IST" duration-ms="177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:47:41 IST" name="setup" finished-at="2025-03-19T20:49:15 IST" duration-ms="94808" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddUserWithDuplicateFeatureCode()[pri:4, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:49:15 IST" name="verifyAddUserWithDuplicateFeatureCode" finished-at="2025-03-19T20:49:19 IST" duration-ms="4003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserWithDuplicateFeatureCode -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:49:19 IST" name="tearDown" finished-at="2025-03-19T20:49:20 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:49:20 IST" name="setup" finished-at="2025-03-19T20:50:23 IST" duration-ms="63718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyMandatoryFieldValidationForAddUser()[pri:5, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:50:23 IST" name="verifyMandatoryFieldValidationForAddUser" finished-at="2025-03-19T20:50:26 IST" duration-ms="2197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMandatoryFieldValidationForAddUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:50:26 IST" name="tearDown" finished-at="2025-03-19T20:50:26 IST" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:50:26 IST" name="setup" finished-at="2025-03-19T20:51:05 IST" duration-ms="39286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddUserUsingLeadingAndTrailingSpaces()[pri:6, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:51:05 IST" name="verifyAddUserUsingLeadingAndTrailingSpaces" finished-at="2025-03-19T20:51:08 IST" duration-ms="3121" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Testabc] but found [ Testabc ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Testabc] but found [ Testabc ]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.TransactionsTest.verifyAddUserUsingLeadingAndTrailingSpaces(TransactionsTest.java:151)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserUsingLeadingAndTrailingSpaces -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:51:08 IST" name="tearDown" finished-at="2025-03-19T20:51:08 IST" duration-ms="166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:51:08 IST" name="setup" finished-at="2025-03-19T20:51:33 IST" duration-ms="24633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySavedTransactionDetailsInEditWindow()[pri:7, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:51:33 IST" name="verifySavedTransactionDetailsInEditWindow" finished-at="2025-03-19T20:54:41 IST" duration-ms="187762" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [1] but found [null],
expected [0] but found [null],
expected [0] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [null],
expected [0] but found [null],
expected [0] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.TransactionsTest.verifySavedTransactionDetailsInEditWindow(TransactionsTest.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySavedTransactionDetailsInEditWindow -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:54:41 IST" name="tearDown" finished-at="2025-03-19T20:54:41 IST" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:54:41 IST" name="setup" finished-at="2025-03-19T20:55:33 IST" duration-ms="52083" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyUserInUsersModuleGridWithPagination()[pri:8, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:55:33 IST" name="verifyUserInUsersModuleGridWithPagination" finished-at="2025-03-19T20:58:41 IST" duration-ms="187689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserInUsersModuleGridWithPagination -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:58:41 IST" name="tearDown" finished-at="2025-03-19T20:58:41 IST" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:58:41 IST" name="setup" finished-at="2025-03-19T20:59:37 IST" duration-ms="55411" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyDeleteUser()[pri:9, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T20:59:37 IST" name="verifyDeleteUser" finished-at="2025-03-19T21:02:46 IST" duration-ms="189122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDeleteUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.TransactionsTest@43bc63a3]" started-at="2025-03-19T21:02:46 IST" name="tearDown" finished-at="2025-03-19T21:02:46 IST" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.TransactionsTest -->
      <class name="test.LogoutTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:56:47 IST" name="setup" finished-at="2025-03-19T21:57:26 IST" duration-ms="39389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLogoutFromLogoutOptionUnderProfile()[pri:1, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:57:26 IST" name="verifyLogoutFromLogoutOptionUnderProfile" finished-at="2025-03-19T21:57:27 IST" duration-ms="1092" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [https://vguard-bt-stg.esealcom.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.LogoutTest.verifyLogoutFromLogoutOptionUnderProfile(LogoutTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogoutFromLogoutOptionUnderProfile -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:57:27 IST" name="tearDown" finished-at="2025-03-19T21:57:27 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:57:27 IST" name="setup" finished-at="2025-03-19T21:58:26 IST" duration-ms="58889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyReLoginImmediatelyAfterLogout()[pri:2, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:58:26 IST" name="verifyReLoginImmediatelyAfterLogout" finished-at="2025-03-19T21:58:27 IST" duration-ms="1099" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [https://vguard-bt-stg.esealcom.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.LogoutTest.verifyReLoginImmediatelyAfterLogout(LogoutTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyReLoginImmediatelyAfterLogout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:58:28 IST" name="tearDown" finished-at="2025-03-19T21:58:28 IST" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:58:28 IST" name="setup" finished-at="2025-03-19T21:59:36 IST" duration-ms="68636" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLogoutAndBackNavigation()[pri:3, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:59:36 IST" name="verifyLogoutAndBackNavigation" finished-at="2025-03-19T21:59:37 IST" duration-ms="1096" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [https://vguard-bt-stg.esealcom.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.LogoutTest.verifyLogoutAndBackNavigation(LogoutTest.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogoutAndBackNavigation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:59:38 IST" name="tearDown" finished-at="2025-03-19T21:59:38 IST" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T21:59:38 IST" name="setup" finished-at="2025-03-19T22:00:47 IST" duration-ms="69516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLogoutAndForwardNavigation()[pri:4, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T22:00:47 IST" name="verifyLogoutAndForwardNavigation" finished-at="2025-03-19T22:00:48 IST" duration-ms="1090" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [https://vguard-bt-stg.esealcom.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.LogoutTest.verifyLogoutAndForwardNavigation(LogoutTest.java:87)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogoutAndForwardNavigation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T22:00:49 IST" name="tearDown" finished-at="2025-03-19T22:00:49 IST" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T22:00:49 IST" name="setup" finished-at="2025-03-19T22:01:55 IST" duration-ms="65817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAutoLogoutAfterSessionTimeout()[pri:5, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T22:01:55 IST" name="verifyAutoLogoutAfterSessionTimeout" finished-at="2025-03-19T22:03:25 IST" duration-ms="90420" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [https://vguard-bt-stg.esealcom.com/admin/home]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [https://vguard-bt-stg.esealcom.com/admin/home]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at test.LogoutTest.verifyAutoLogoutAfterSessionTimeout(LogoutTest.java:94)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAutoLogoutAfterSessionTimeout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:test.LogoutTest@ba2f4ec]" started-at="2025-03-19T22:03:25 IST" name="tearDown" finished-at="2025-03-19T22:03:25 IST" duration-ms="201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.LogoutTest -->
    </test> <!-- Test -->
  </suite> <!-- Smoke -->
</testng-results>
