<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DSR" failures="0" tests="12" name="test.LoginTest" time="91.394" errors="1" timestamp="2025-03-19T00:26:45 IST" skipped="0">
  <testcase classname="test.LoginTest" name="verifyLoginPageTitleAndUrl" time="5.288">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&quot; because &quot;this.extentTest&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.extentTest" is null
at test.LoginTest.verifyLoginPageTitleAndUrl(LoginTest.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyLoginPageTitleAndUrl -->
  <testcase classname="test.LoginTest" name="verifyFieldAndCheckboxLabels" time="5.450"/>
  <testcase classname="test.LoginTest" name="verifyLoginUsingValidCredentials" time="6.273"/>
  <testcase classname="test.LoginTest" name="verifyLoginUsingInvalidCredentials" time="6.548"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithInvalidEmailAndValidPassword" time="16.148"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithValidEmailAndInvalidPassword" time="16.557"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithBlankCredentials" time="6.178"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithEmailOnly" time="5.585"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithPasswordOnly" time="5.526"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithShortPassword" time="5.677"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithUppercaseInsensitiveEmail" time="6.032"/>
  <testcase classname="test.LoginTest" name="verifyLoginWithLowercaseInsensitiveEmail" time="6.132"/>
</testsuite> <!-- test.LoginTest -->
